### ISSUE TITLE
无数据.ini文件

### ISSUE THREAD

**Issue by ShuibeiC** [hd80606b/xiaoquduo#1]
下载并解压后发现无所说 的“数据.ini”文件

**Comment by hd80606b** [comment]
可能是我忘记打包进去了，不过第一次运行程序会自动在那个目录下释放出“数据.ini”文件

**Comment by ShuibeiC** [comment]
> 可能是我忘记打包进去了，不过第一次运行程序会自动在那个目录下释放出“数据.ini”文件

能重新在上传一次吗，我安装环境之后还是无法运行，但是在vs2019里面可以打开，显示cookie失效

**Comment by hd80606b** [comment]
嗯，我马上来传一份，顺便发现了一个bug，等会一起更新

**Comment by ShuibeiC** [comment]
好的好的

**Comment by hd80606b** [comment]
整好了，再看看

**Comment by ShuibeiC** [comment]
完美，大佬牛逼

**Comment by hd80606b** [comment]
想要一个star（
